[config]
schemaVersion = "0.0.1"

[package]
namespace = "molenzwiebel"
name = "Wetstone"
versionNumber = "1.2.0"
description = "Plugin framework and general utilities for V Rising mods."
websiteUrl = "https://github.com/molenzwiebel/Wetstone"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.0.0"

[build]
icon = "./icon.png"
readme = "./README-TS.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]
categories = []